const $=id=>document.getElementById(id), KEY='cambio-rates-v1';
let rates=null,currency='CLP',installPrompt=null;
const names={CLP:'Pesos chilenos',ARS:'Pesos argentinos',USD:'Dólares estadounidenses'};
function validRates(r){return r&&Number.isFinite(r.blue)&&r.blue>0&&Number.isFinite(r.clp)&&r.clp>0&&Number.isFinite(Date.parse(r.blueDate))&&Number.isFinite(Date.parse(r.clpDate));}
try{const saved=JSON.parse(localStorage.getItem(KEY));if(validRates(saved))rates=saved;}catch{}
function parseAmount(raw){const s=raw.trim().replace(/\s/g,'');if(!s)return null;let n;if(/^\d{1,3}(\.\d{3})+(,\d{1,2})?$/.test(s))n=Number(s.replaceAll('.','').replace(',','.'));else if(/^\d+([.,]\d{1,2})?$/.test(s))n=Number(s.replace(',','.'));else return null;return Number.isFinite(n)&&n<=1e15?n:null;}
function conversions(amount,from){const usd=from==='USD'?amount:from==='ARS'?amount/rates.blue:amount/rates.clp;return {CLP:usd*rates.clp,ARS:usd*rates.blue,USD:usd};}
function money(value){return new Intl.NumberFormat('es-AR',{minimumFractionDigits:2,maximumFractionDigits:2}).format(value);}
function render(){const amount=parseAmount($('amount').value);$('input-error').hidden=amount!==null;$('input-code').textContent=currency;const values=rates&&amount!==null?conversions(amount,currency):null;$('results').replaceChildren(...Object.keys(names).filter(c=>c!==currency).map(c=>{const div=document.createElement('div');div.className='result';const label=document.createElement('p');label.className='result-label';label.textContent=names[c];const value=document.createElement('p');value.className='result-value';value.textContent=values?money(values[c]):'—';const code=document.createElement('div');code.className='result-code';code.textContent=c;div.append(label,value,code);return div;}));if(rates){$('blue-rate').textContent=money(rates.blue)+' ARS / USD';$('clp-rate').textContent=money(rates.clp)+' CLP / USD';$('blue-date').textContent='DolarAPI · '+new Date(rates.blueDate).toLocaleString('es-AR',{dateStyle:'short',timeStyle:'short'});$('clp-date').textContent='Mindicador · '+new Date(rates.clpDate).toLocaleDateString('es-CL',{timeZone:'America/Santiago'});}}
async function getJSON(url){const response=await fetch(url,{signal:AbortSignal.timeout(12000),cache:'no-store'});if(!response.ok)throw Error('API no disponible');return response.json();}
async function refresh(){const button=$('refresh');button.disabled=true;button.textContent='Actualizando…';$('status').textContent=rates?'Actualizando. Mostramos las últimas cotizaciones guardadas.':'Consultando cotizaciones…';try{const [blue,chile]=await Promise.all([getJSON('https://dolarapi.com/v1/dolares/blue'),getJSON('https://mindicador.cl/api/dolar')]);const points=chile.serie?.filter(p=>Number.isFinite(p.valor)&&p.valor>0&&Number.isFinite(Date.parse(p.fecha))).sort((a,b)=>Date.parse(b.fecha)-Date.parse(a.fecha));const next={blue:blue.venta,blueDate:blue.fechaActualizacion,clp:points?.[0]?.valor,clpDate:points?.[0]?.fecha,fetchedAt:new Date().toISOString()};if(!validRates(next))throw Error('Cotizaciones inválidas');rates=next;try{localStorage.setItem(KEY,JSON.stringify(rates));}catch{}$('status').textContent='Últimos datos disponibles. El dólar observado chileno se publica por día hábil.';}catch{$('status').textContent=rates?'No pudimos actualizar. Usamos las cotizaciones guardadas; revisá sus fechas.':'No pudimos obtener las cotizaciones. Revisá tu conexión y tocá Actualizar.';}finally{button.disabled=false;button.textContent='Actualizar';render();}}
$('amount').addEventListener('input',render);document.querySelectorAll('[name=currency]').forEach(input=>input.addEventListener('change',()=>{currency=input.value;render();}));$('refresh').addEventListener('click',refresh);
window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();installPrompt=e;$('install').hidden=false;});$('install').addEventListener('click',async()=>{if(installPrompt){await installPrompt.prompt();installPrompt=null;$('install').hidden=true;}});window.addEventListener('appinstalled',()=>{$('install').hidden=true;});
if('serviceWorker'in navigator)navigator.serviceWorker.register('./sw.js').catch(()=>{});
if(document.modelContext?.registerTool){try{Promise.resolve(document.modelContext.registerTool({name:'convert_currency',title:'Convertir monedas',description:'Actualiza el monto y la moneda del conversor y devuelve equivalencias con blue venta.',inputSchema:{type:'object',properties:{amount:{type:'number',minimum:0,maximum:1e15},currency:{type:'string',enum:['CLP','ARS','USD']}},required:['amount','currency'],additionalProperties:false},annotations:{readOnlyHint:false},execute(input){if(!input||!Number.isFinite(input.amount)||input.amount<0||input.amount>1e15||!Object.hasOwn(names,input.currency))throw Error('Monto o moneda inválidos');if(!rates)throw Error('Cotizaciones no disponibles');currency=input.currency;$('amount').value=input.amount.toFixed(2).replace('.',',');document.querySelector(`[name=currency][value=${currency}]`).checked=true;render();return {values:conversions(input.amount,currency),rates};}})).catch(()=>{});}catch{}}
render();refresh();
